auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 0


common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

# 👇 Add this block to allow boltdb-shipper without structured metadata

limits_config:
  allow_structured_metadata: true   # 👈 allow OTLP structured metadata
  ingestion_rate_mb: 16             # (whatever you already have is fine)

schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
