spring:
  application:
    name: mfms

  datasource:
    url: jdbc:postgresql://mfms-db:5432/postgres
    username: mfms
    password: mfms
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.default_schema: mfms
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: mfms
    locations: classpath:db/migration


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  tracing:
    enabled: true
    sampling:
      probability: 1.0

  otel:
    service:
      name: mfms

  otlp:
    tracing:
      endpoint: http://otel-collector:4317
      export:
        enabled: true
    logging:
      endpoint: http://otel-collector:4318/v1/logs
      export:
        enabled: true
    metrics:
      endpoint: http://otel-collector:4318/v1/metrics
      export:
        enabled: true

  metrics:
    export:
      otlp:
        enabled: true
        endpoint: http://otel-collector:4318/v1/metrics
    tags:
      service.name: mfms
    enable:
      jvm: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  trading: "Asia/Kolkata"

