global:
  scrape_interval: 15s

scrape_configs:
  # Scrape the OTEL Collector's Prometheus exporter (which exposes your app metrics)
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']
  # Exported application metrics from collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: [ 'otel-collector:8889' ]
