create table mfms.fund
(
    symbol varchar(255) primary key,
    name   varchar(255) not null
);

create table mfms.user_account
(
    username      varchar(255) primary key,
    enabled       boolean      not null,
    password_hash varchar(255) not null,
    role          varchar(255) not null
        check (role in ('ADMIN', 'USER'))
);

create table mfms.holding
(
    id          bigint generated by default as identity primary key,
    units       numeric(19, 6),
    username    varchar(255) not null
        references user_account (username)
            on delete cascade on update cascade,
    version     bigint       not null,
    fund_symbol varchar(255) not null
        references fund (symbol)
            on delete cascade on update cascade,
    unique (username, fund_symbol)
);

create table mfms.nav
(
    id          bigint generated by default as identity primary key,
    date        date           not null,
    nav         numeric(19, 6) not null,
    fund_symbol varchar(255)   not null
        references fund (symbol)
            on delete cascade on update cascade,
    unique (fund_symbol, date)
);

create table mfms.trade
(
    id          bigint generated by default as identity primary key,
    amount      numeric(19, 6) not null,
    nav         numeric(19, 6) not null,
    ts          timestamp(6) with time zone default now(),
    type        varchar(255)   not null
        check (type in ('BUY', 'REDEEM')),
    units       numeric(19, 6) not null,
    username    varchar(255)   not null
        references user_account (username)
            on delete cascade on update cascade,
    fund_symbol varchar(255)   not null
        references fund (symbol)
            on delete cascade on update cascade
);




-- Indexes for faster joins and lookups
create index idx_holding_user on mfms.holding (username);
create index idx_trade_user on mfms.trade (username);
create index idx_trade_fund on mfms.trade (fund_symbol);
create index idx_nav_fund_date on mfms.nav (fund_symbol, date);
